# Generated by Django 4.2.4 on 2023-10-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
