# Generated by Django 4.2.4 on 2023-12-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
