# Generated by Django 4.2.6 on 2023-10-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='review',
            new_name='reviews',
        ),
    ]
